version: 1
jobs:
  build:
    docker:
      - image: thomthomgo/mononunit:1
    steps:
      - checkout
      - run:
          name: Prepare Build
          command: chmod +x ./CI/prebuild.sh && ./CI/prebuild.sh
      - run:
          name: Build sln
          command: chmod +x ./CI/build.sh && ./CI/build.sh
      - run:
          name: Unit tests
          command: chmod +x ./CI/test.sh && ./CI/test.sh
